#!/bin/bash

# Run to start the whole system up, 5 services (one is nginx)
# `./run``
# Or, run with a parameter service name (from docker-compose) to restart just that service
# `./run meminator`

set -x # print what you run
set -e 

docker compose up --build -d $*

source .env
// if the first argument is python, nodejs, dotnet, or java, override whatever was in .env
if [[ "$1" == "python" || "$1" == "nodejs" || "$1" == "dotnet" || "$1" == "java" ]]; then
  PROGRAMMING_LANGUAGE=$1
fi
export PROGRAMMING_LANGUAGE
./scripts/honeycomb-whoami.sh

echo "http://localhost:10114"
