#!/bin/bash

# Run to start the whole system up, 5 services (one is nginx)
# `./run``
# Or, run with a parameter service name (from docker-compose) to restart just that service
# `./run meminator`

set -x # print what you run
set -e

if [[ "$1" == "python" || "$1" == "nodejs" || "$1" == "dotnet" ]]; then
  PROGRAMMING_LANGUAGE_FROM_ARG=$1
  echo "Using $PROGRAMMING_LANGUAGE_FROM_ARG as programming language"
  shift
fi

docker compose up --build -d $*

source .env
# if the first argument is python, nodejs, or dotnet, override whatever was in .env
if [[ -n "$PROGRAMMING_LANGUAGE_FROM_ARG" ]]; then
  export PROGRAMMING_LANGUAGE=$PROGRAMMING_LANGUAGE_FROM_ARG
fi
export PROGRAMMING_LANGUAGE
./scripts/honeycomb-whoami.sh

echo "http://localhost:10114"
